//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnopeMerge.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnopeMerge.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT BotInfo
        ///ID 1
        ///DATA nick BotServ
        ///DATA user services
        ///DATA host services.nite-serv.com
        ///DATA realname Bot Service
        ///DATA created 1361509363
        ///DATA oper_only 0
        ///END.
        /// </summary>
        internal static string BotInfoSingularTextStream {
            get {
                return ResourceManager.GetString("BotInfoSingularTextStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT BotInfo
        ///ID 1
        ///DATA nick BotServ
        ///DATA user services
        ///DATA host services.nite-serv.com
        ///DATA realname Bot Service
        ///DATA created 1361509363
        ///DATA oper_only 0
        ///END
        ///OBJECT BotInfo
        ///ID 2
        ///DATA nick ChanServ
        ///DATA user services
        ///DATA host services.nite-serv.com
        ///DATA realname Channel Registration Service
        ///DATA created 1361509363
        ///DATA oper_only 0
        ///END
        ///OBJECT BotInfo
        ///ID 3
        ///DATA nick Global
        ///DATA user services
        ///DATA host services.nite-serv.com
        ///DATA realname Global Noticer
        ///DATA created 1361509363
        ///DATA oper_only 0
        ///END.
        /// </summary>
        internal static string BotInfoTextStream {
            get {
                return ResourceManager.GetString("BotInfoTextStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT NickCore
        ///ID 80
        ///DATA display Cotsuma
        ///DATA pass sha256:9951fda25fabe2afebca34107c34f6333c771abfc1a9145a31f8ce8c7d83b218:130d7a9447944a940aaba52004ac28db0aeedf644f33bf6b2bce0df971ea9152
        ///DATA email begamache@gmail.com
        ///DATA language en_US
        ///DATA access *Cotsuma@*.cpe.cableone.net 
        ///DATA memomax 30
        ///DATA MEMO_SIGNON 1
        ///DATA MEMO_RECEIVE 1
        ///DATA HIDE_EMAIL 1
        ///DATA NS_PRIVATE 1
        ///DATA AUTOOP 1
        ///DATA KILLPROTECT 1
        ///DATA NS_SECURE 1
        ///END
        ///OBJECT NickCore
        ///ID 4
        ///DATA display crysis
        ///DATA pass sha256:60c07c3627f17da07575c2264c0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NickCoreMultiTextStream {
            get {
                return ResourceManager.GetString("NickCoreMultiTextStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT NickCore
        ///ID 6
        ///DATA display Apophis
        ///DATA pass sha256:67749f82c3b8710444c6a3419fa27ce5d9844693c0a2179cda2ad627350ce1db:41fd0d82182f916361b72a2b05f5c4bd45f8e9573b6417334046a6290c5e276c
        ///DATA email services@nite-serv.com
        ///DATA language 
        ///DATA memomax 20
        ///DATA MEMO_SIGNON 1
        ///DATA MEMO_RECEIVE 1
        ///DATA HIDE_EMAIL 1
        ///DATA HIDE_MASK 1
        ///DATA NS_PRIVATE 1
        ///DATA AUTOOP 1
        ///DATA NS_SECURE 1
        ///DATA NS_STATS 1
        ///END
        ///OBJECT NickCore
        ///ID 8
        ///DATA display Baddog13
        ///DATA pass sha256:9e4bd2277fdffab078ff642da74eadfa0ce67d58dd42eddad6c474e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NickCoreWithDuplicateValue {
            get {
                return ResourceManager.GetString("NickCoreWithDuplicateValue", resourceCulture);
            }
        }
    }
}
